# Generated by Django 4.1 on 2022-09-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='events',
            new_name='eventName',
        ),
    ]
