# Generated by Django 4.1 on 2022-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_events_events_eventname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('userList', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
